version: '3.8'

services:
  php:
    container_name: php
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    ports:
      - '9000:9000'
    volumes:
      - ./app:/var/www/symfony_docker