controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

redirect:
    path: '/'
    controller: App\Controller\RedirectController::redirectToLocale
login:
    path: /login
